### ISSUE TITLE
inspec.yml baseline path correction

### ISSUE THREAD

**Issue by aaronlippold** [CMSgov/cms-ars-3.1-moderate-aws-rds-crunchy-data-postgresql-9-stig-overlay#1]
currently inspec.yml says:
depends:
- name: aws-rds-crunchy-data-postgresql-9-stig-baseline
  git: https://github.com/mitre/aws-rds-crunchy-data-postgresql-9-stig-baseline.git
  branch: master

but based on the README instructions should say:
depends:
- name: aws-rds-crunchy-data-postgresql-9-stig-baseline
  path: ../aws-rds-crunchy-data-postgresql-9-stig-baseline

**Comment by karikarshivani** [comment]
PR #2 addresses this
